{% set name = "xeus-cling" %}
{% set version = "0.4.4" %}
{% set sha256 = "45d5843e58c411a2588f439b8c3106f37966273c959c6b118a404d79f02c32ad" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://github.com/QuantStack/xeus-cling/archive/{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  features:
    - vc14    # [win and py36]
  skip: true  # [win and py<36]
  number: 0

requirements:
  build:
    - toolchain
    - cmake
    - cppzmq
    - zeromq
    - cryptopp
    - cling >=0.5,<0.6
    - xeus >=0.12.0,<0.13
    - xtl >=0.4.0,<0.5
    - pugixml
    - cxxopts >=2.1.0,<3.0
    - nlohmann_json >=3.1.1,<4.0
    - dirent >=1.21,<2.0        # [win]
  run:
    - xeus >=0.12.0,<0.13
    - zeromq
    - cryptopp
    - util-linux                 # [linux]
    - cling  >=0.5,<0.6
    - cppzmq                     # Even though cppzmq is header-only, it is used at runtime by the interpreted c++
    - xtl  >=0.4.0,<0.5          # Even though xtl is header-only, it is used at runtime by the interpreted c++
    - nlohmann_json >=3.1.1,<4.0 # Even though nlohmann_json is header-only, it is used at runtime by the interpreted c++

test:
  commands:
    - test -f ${PREFIX}/bin/xeus-cling  # [unix]
    - if exist %LIBRARY_PREFIX%\bin\xeus-cling.exe (exit 0) else (exit 1)  # [win]

about:
  home: http://quantstack.net/xeus-cling
  license: BSD 3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: 'Cling-based C++ kernel for Jupyter based on xeus'
  description: 'xeus is a library meant to facilitate the implementation of kernels for Jupyter. It takes the burden of implementing the Jupyter Kernel protocol so developers can focus on implementing the interpreter part of the Kernel.'
  doc_url: http://xeus-cling.readthedocs.io
  dev_url: https://github.com/QuantStack/xeus-cling

extra:
  recipe-maintainers:
    - SylvainCorlay
    - JohanMabille
    - gouarin
